site_name: Documentación de mi proyecto
site_url: https://laucanmol.github.io/Proyecto_Laura_Cambra-mkdocs/
site_author: Laura Cambra Molina
site_description: Guía rápida MkDocs

theme: 
  name: material

  




nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Instalación: instalacion.md
  - Uso del proyecto: uso.md
