site_name: Documentación de mi proyecto
site_url: https://laucanmol.github.io/Proyecto_Laura_Cambra-mkdocs/
theme: 
  name: material
  Author : Laura Cambra Molina
  Content : Guia rapida mkdocs




nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Instalación: instalacion.md
  - Uso del proyecto: uso.md
